name: Build Windows exe

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'          # v1.0.0 のようなタグを push した時も同じビルドを実行
  workflow_dispatch:
    inputs:
      ref:
        description: 'Commit SHA, branch, or tag to build'
        required: false
        default: ''

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install fyne CLI
        run: go install fyne.io/tools/cmd/fyne@v1.7.0

      - name: Install dependencies
        run: go mod tidy

      - name: Build Windows executable (no console)
        run: |
          fyne package -os windows -icon app.ico -name photo-date-aligner -release -app-id io.github.p95095yy.photodatealigner

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: photo-date-aligner-windows
          path: photo-date-aligner.exe
