name: Build macOS Universal app

on:
  push:
    branches:
      - main
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install fyne CLI
        run: go install fyne.io/tools/cmd/fyne@v1.7.0

      - name: Install dependencies
        run: go mod tidy

      - name: Install ImageMagick
        run: brew install imagemagick

      - name: Convert .ico to high-res .png
        run: |
          # ICO内のすべてのPNGを展開
          magick convert app.ico app-%02d.png
          
          # 最大サイズのPNGを選択
          largest_png=$(identify -format "%w %h %f\n" app-*.png | \
            awk '{print $1*$2, $3}' | sort -nr | head -n1 | awk '{print $2}')
          
          echo "Using largest icon: $largest_png"
          cp "$largest_png" app.png

      - name: Verify PNG file
        run: |
          identify app.png
          file app.png
          ls -lh app.png
          
      - name: Build macOS app bundle (${{ matrix.arch }})
        run: |
          env CGO_ENABLED=1 GOOS=darwin GOARCH=${{ matrix.arch }} fyne package \
            -os darwin -icon app.png -name photo-date-aligner \
            -release -app-id io.github.p95095yy.photodatealigner
          
          mv "photo-date-aligner.app" "photo-date-aligner-${{ matrix.arch }}.app"

      - name: Upload per-arch artifact
        uses: actions/upload-artifact@v4
        with:
          name: photo-date-aligner-${{ matrix.arch }}
          path: photo-date-aligner-${{ matrix.arch }}.app

  merge:
    runs-on: macos-latest
    needs: build
    steps:
      - name: Download amd64
        uses: actions/download-artifact@v4
        with:
          name: photo-date-aligner-amd64
          path: .

      - name: Download arm64
        uses: actions/download-artifact@v4
        with:
          name: photo-date-aligner-arm64
          path: .
          
      - name: Verify apps
        run: ls -R

      - name: Merge into Universal Binary
        run: |
          mkdir -p merged/Contents/MacOS
          cp -R photo-date-aligner-amd64.app merged/
          
          lipo -create \
            photo-date-aligner-amd64.app/Contents/MacOS/photo-date-aligner \
            photo-date-aligner-arm64.app/Contents/MacOS/photo-date-aligner \
            -output merged/Contents/MacOS/photo-date-aligner
          
          mv merged "photo-date-aligner.app"

      - name: Zip Universal app
        run: |
          ditto -c -k --sequesterRsrc --keepParent \
            "photo-date-aligner.app" "photo-date-aligner-macos-universal.zip"

      - name: Upload Universal Binary
        uses: actions/upload-artifact@v4
        with:
          name: photo-date-aligner-macos-universal
          path: photo-date-aligner-macos-universal.zip
